// frontend/src/app/[conference]/[...slug]/page.tsx
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { getConference } from '@/data/getConference';
import { getItemByPathOrDefault } from '@/data/umbraco/getItemByPath';
import { generateMetadata as generateSpeakerMetadata } from '@/components/pageTypes/SpeakerDetailPage';

export interface PageProps {
    params: {
        conference: string;
        slug: string[];
    };
}

export async function generateMetadata({
    params,
}: PageProps): Promise<Metadata> {
    const { conference, item } = await getData(params);

    if (!conference || !item) {
        return notFound();
    }

    switch (item.contentType) {
        case 'speaker':
            return await generateSpeakerMetadata({ conference, speaker: item });
    }

    return {};
}

export default async function Page({ params }: PageProps) {
    const { conference, item } = await getData(params);

    if (!conference || !item) {
        return notFound();
    }

    switch (item.contentType) {
        case 'speaker':
            const { SpeakerDetailPage } = await import(
                '@/components/pageTypes/SpeakerDetailPage'
            );

            return <SpeakerDetailPage conference={conference} speaker={item} />;
        case 'page':
            const { GenericPage } = await import(
                '@/components/pageTypes/GenericPage'
            );

            return (
                <GenericPage
                    params={params}
                    conference={conference}
                    page={item}
                />
            );
        default:
            return notFound();
    }
}

async function getData(params: PageProps['params']) {
    const conference = await getConference(params.conference);

    if (!conference) {
        return {};
    }

    const item = await getItemByPathOrDefault(
        `${params.conference}/${params.slug.join('/')}`,
    );

    if (!item) {
        return { conference };
    }

    return { conference, item };
}

// src/routes/[conference]/[...slug]/+page.svelte
<script lang="ts">
    import ChildPageShell from '#lib/components/ChildPageShell.svelte';
    import GenericPage from '#lib/components/GenericPage.svelte';
    import SpeakerDetailPage from '#lib/components/SpeakerDetailPage.svelte';
    import type { PageProps } from './$types';

    let { data }: PageProps = $props();

    const routeParams = $derived({ conference: data.conferenceSlug });
    const pageParams = $derived({
        conference: data.conferenceSlug,
        slug:
            data.item.route.path
                ?.replace(new RegExp(`^/${data.conferenceSlug}/?`), '')
                .split('/')
                .filter(Boolean) ?? [],
    });
</script>

<ChildPageShell
    conference={data.conference}
    params={routeParams}
    sponsors={data.layoutSponsors}
>
    {#if data.item.contentType === 'speaker'}
        <SpeakerDetailPage speaker={data.item} sessions={data.sessions ?? []} />
    {:else}
        <GenericPage
            params={pageParams}
            conference={data.conference}
            page={data.item}
            schedule={data.schedule}
            sponsors={data.sponsors}
        />
    {/if}
</ChildPageShell>
