// src/lib/components/Button.svelte
<script lang="ts">
    import { imageUrl } from '#lib/imageUrl.ts';
    import type { CmsLink } from '#lib/types.ts';
    import type { Snippet } from 'svelte';

    interface Props {
        cmsLink?: CmsLink;
        url?: string | null;
        children?: Snippet;
        class?: string;
    }

    const buttonClasses = 'button block';

    let { cmsLink, url, children, class: className }: Props = $props();

    const combinedClass = $derived(
        className ? `${buttonClasses} ${className}` : buttonClasses,
    );

    const label = $derived(cmsLink?.title ?? '');

    function linkWithQuery(
        baseUrl: string,
        queryString?: string | null,
    ): string {
        return queryString ? baseUrl + queryString : baseUrl;
    }

    const resolved = $derived.by(() => {
        if (cmsLink) {
            const { route, queryString, target } = cmsLink;

            if (cmsLink.linkType === 'Content' && route?.path) {
                return {
                    kind: 'anchor' as const,
                    href: linkWithQuery(route.path, queryString),
                    target: target || undefined,
                };
            }

            if (cmsLink.linkType === 'External' && cmsLink.url) {
                return {
                    kind: 'anchor' as const,
                    href: linkWithQuery(cmsLink.url, queryString),
                    target: target || undefined,
                };
            }

            if (cmsLink.linkType === 'Media' && cmsLink.url) {
                return {
                    kind: 'anchor' as const,
                    href: imageUrl(linkWithQuery(cmsLink.url, queryString)),
                    target: target || undefined,
                };
            }

            return { kind: 'button' as const };
        }

        if (!url) {
            return { kind: 'button' as const };
        }

        const isExternalUrl =
            url.startsWith('https://') || url.startsWith('http://');

        return {
            kind: 'anchor' as const,
            href: url,
            target: isExternalUrl ? '_blank' : undefined,
        };
    });
</script>

{#if resolved.kind === 'anchor'}
    <a class={combinedClass} href={resolved.href} target={resolved.target}>
        {#if children}
            {@render children()}
        {:else}
            {label}
        {/if}
    </a>
{:else}
    <button class={combinedClass}>
        {#if children}
            {@render children()}
        {:else}
            {label}
        {/if}
    </button>
{/if}

// src/components/Button.tsx
import Link from 'next/link';
import type { CmsLink } from '@/data/types';
import { imageUrl } from '@/data/umbraco/imageUrl';

export type ButtonProps = UrlButtonProps | CmsButtonProps;

const buttonClasses = 'button block';

export function Button({ className, children, ...props }: ButtonProps) {
    if ('cmsLink' in props) {
        return (
            <CmsButton className={className} cmsLink={props.cmsLink}>
                {children}
            </CmsButton>
        );
    }

    return (
        <UrlButton className={className} url={props.url}>
            {children}
        </UrlButton>
    );
}

export interface CmsButtonProps {
    cmsLink: CmsLink;
    children?: string | null;
    className?: string;
}

export function CmsButton({ cmsLink, children, className }: CmsButtonProps) {
    className = `${buttonClasses}${className ? className : ''}`;

    const { route, url, queryString, title } = cmsLink;

    const target = cmsLink.target ? cmsLink.target : undefined;

    if (cmsLink.linkType === 'Content' && route?.path) {
        const path = queryString ? route.path + queryString : route.path;

        return (
            <Link className={className} href={path} target={target}>
                {children ?? title}
            </Link>
        );
    }

    if (cmsLink.linkType === 'External' && url) {
        const combinedUrl = queryString ? url + queryString : url;

        return (
            <a className={className} href={combinedUrl} target={target}>
                {children ?? title}
            </a>
        );
    }

    if (cmsLink.linkType === 'Media' && url) {
        const combinedUrl = queryString ? url + queryString : url;

        return (
            <a
                className={className}
                href={imageUrl(combinedUrl)}
                target={target}
            >
                {children ?? title}
            </a>
        );
    }

    return <button className={className}>{children ?? title}</button>;
}

export interface UrlButtonProps {
    url: string;
    children?: string | null;
    className?: string;
}

export function UrlButton({ className, url, children }: UrlButtonProps) {
    className = `${buttonClasses}${className ? className : ''}`;

    if (!url) {
        return <button className={className}>{children}</button>;
    }

    const isExternalUrl =
        url.startsWith('https://') || url.startsWith('http://');

    if (isExternalUrl) {
        return (
            <a className={className} href={url} target="_blank">
                {children}
            </a>
        );
    }

    return (
        <Link className={className} href={url}>
            {children}
        </Link>
    );
}
