// frontend/src/components/pageTypes/GenericPage.tsx
import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import type {
    ContentBlock,
    Page,
    ParsedConference,
    Schedule,
    Sponsors,
} from '@/data/types';
import type { PageProps } from '@/app/[conference]/[...slug]/page';
import { imageUrl } from '@/data/umbraco/imageUrl';
import { getSchedule } from '@/data/getSchedule';
import { getSponsors } from '@/data/getSponsors';

export interface GenericPageProps extends PageProps {
    conference: ParsedConference;
    page: Page;
}

const OG_IMAGE_WIDTH = 1200;
const OG_IMAGE_HEIGHT = 630;

export async function generateMetadata({
    page,
}: GenericPageProps): Promise<Metadata> {
    const {
        title,
        metaDescription,
        openGraphImage: openGraphImages,
    } = page.properties ?? {};
    const [openGraphImage] = openGraphImages ?? [];

    const metadata: Metadata = {};

    if (title) {
        metadata.title = title;
    }

    if (metaDescription) {
        metadata.description = metaDescription;
    }

    if (openGraphImage?.url) {
        const url = imageUrl(openGraphImage.url, {
            width: OG_IMAGE_WIDTH,
            height: OG_IMAGE_HEIGHT,
        });

        metadata.openGraph = {
            images: [
                {
                    url,
                    width: OG_IMAGE_WIDTH,
                    height: OG_IMAGE_HEIGHT,
                },
            ],
        };
    }

    return metadata;
}
const IntroAndEmailSignupBlock = dynamic(() =>
    import('@/components/contentBlocks/IntroAndEmailSignupBlock').then(
        (mod) => mod.IntroAndEmailSignupBlock,
    ),
);

const ScheduleBlock = dynamic(() =>
    import('@/components/contentBlocks/ScheduleBlock').then(
        (mod) => mod.ScheduleBlock,
    ),
);

const LocationBlock = dynamic(() =>
    import('@/components/contentBlocks/LocationBlock').then(
        (mod) => mod.LocationBlock,
    ),
);

const SponsorsBlock = dynamic(() =>
    import('@/components/contentBlocks/SponsorsBlock').then(
        (mod) => mod.SponsorsBlock,
    ),
);

const RichTextBlock = dynamic(() =>
    import('@/components/contentBlocks/RichTextBlock').then(
        (mod) => mod.RichTextBlock,
    ),
);

const TextWithButtonsBlock = dynamic(() =>
    import('@/components/contentBlocks/TextWithButtonsBlock').then(
        (mod) => mod.TextWithButtonsBlock,
    ),
);

export async function GenericPage({
    params,
    conference,
    page,
}: GenericPageProps) {
    const blocks =
        page.properties?.blocks?.items?.map((item) => item.content) ?? [];

    const { schedule, sponsors } = await getPageDataForBlocks(
        conference,
        blocks,
    );

    return (
        <>
            {blocks.map((block) => {
                switch (block.contentType) {
                    case 'introAndEmailSignupBlock':
                        return (
                            <IntroAndEmailSignupBlock
                                key={block.id}
                                params={params}
                            />
                        );
                    case 'scheduleBlock':
                        return (
                            <ScheduleBlock
                                key={block.id}
                                conference={conference}
                                schedule={schedule}
                            />
                        );
                    case 'locationBlock':
                        return <LocationBlock key={block.id} />;
                    case 'sponsorsBlock':
                        return (
                            <SponsorsBlock key={block.id} sponsors={sponsors} />
                        );
                    case 'richText':
                        return <RichTextBlock key={block.id} block={block} />;
                    case 'textWithButtons':
                        return (
                            <TextWithButtonsBlock
                                key={block.id}
                                block={block}
                            />
                        );
                }
            })}
        </>
    );
}

export interface AdditionalPageData {
    schedule?: Schedule;
    sponsors?: Sponsors;
}

export async function getPageDataForBlocks(
    conference: ParsedConference,
    blocks: ContentBlock[],
): Promise<AdditionalPageData> {
    const pageData: AdditionalPageData = {};
    const tasks: Promise<void>[] = [];

    if (blocks.find((block) => block.contentType === 'scheduleBlock')) {
        tasks.push(
            getSchedule(conference.id).then((schedule) => {
                pageData.schedule = schedule;
            }),
        );
    }

    if (blocks.find((block) => block.contentType === 'sponsorsBlock')) {
        tasks.push(
            getSponsors(conference.id).then((sponsors) => {
                pageData.sponsors = sponsors;
            }),
        );
    }

    await Promise.all(tasks);

    return pageData;
}

// src/lib/components/GenericPage.svelte
<script lang="ts">
    import IntroAndEmailSignupBlock from '#lib/components/IntroAndEmailSignupBlock.svelte';
    import LocationBlock from '#lib/components/LocationBlock.svelte';
    import RichTextBlock from '#lib/components/RichTextBlock.svelte';
    import ScheduleBlock from '#lib/components/ScheduleBlock.svelte';
    import SponsorsBlock from '#lib/components/SponsorsBlock.svelte';
    import TextWithButtonsBlock from '#lib/components/TextWithButtonsBlock.svelte';
    import { getPageBlocks } from '#lib/pageBlocks.ts';
    import type {
        Page,
        ParsedConference,
        Schedule,
        Sponsors,
    } from '#lib/types.ts';

    interface Props {
        params: {
            conference: string;
            slug?: string[];
        };
        conference: ParsedConference;
        page: Page;
        schedule?: Schedule;
        sponsors?: Sponsors;
    }

    let { params, conference, page, schedule, sponsors }: Props = $props();

    const blocks = $derived(getPageBlocks(page));
</script>

{#each blocks as block (block.id)}
    {#if block.contentType === 'introAndEmailSignupBlock'}
        <IntroAndEmailSignupBlock {params} />
    {:else if block.contentType === 'scheduleBlock'}
        <ScheduleBlock {conference} {schedule} />
    {:else if block.contentType === 'locationBlock'}
        <LocationBlock />
    {:else if block.contentType === 'sponsorsBlock'}
        <SponsorsBlock {sponsors} />
    {:else if block.contentType === 'richText'}
        <RichTextBlock {block} />
    {:else if block.contentType === 'textWithButtons'}
        <TextWithButtonsBlock {block} />
    {/if}
{/each}
