// frontend/src/components/OveItEmbed.tsx
'use client';
import { useCallback, useEffect, useRef } from 'react';
import { parseUrl } from '@/util';

export interface InlineScriptProps {
    embedUrl: string;
}

export function OveItEmbed({ embedUrl }: InlineScriptProps) {
    const iframeRef = useRef<HTMLIFrameElement>(null);
    const parsedUrl = parseUrl(embedUrl);

    const sendInfo = useCallback(
        (time: number) => {
            iframeRef.current?.contentWindow?.postMessage(
                {
                    type: 'info',
                    referrer: window.location.href,
                    embedID: parsedUrl?.searchParams.get('id'),
                    time: time,
                },
                '*',
            );
        },
        [parsedUrl?.searchParams],
    );

    const resizeIframe = useCallback((dimensions: { height: number }) => {
        if (!iframeRef.current) {
            return;
        }

        if (isNaN(dimensions.height)) {
            dimensions.height = 800;
        }
        iframeRef.current.style.height = dimensions.height + 'px';
    }, []);

    useEffect(() => {
        function onWindowMessage(event: MessageEvent) {
            if (event.source != iframeRef.current?.contentWindow) {
                return;
            }

            switch (event.data.type) {
                case 'resize':
                    resizeIframe(event.data);
                    break;
                case 'info':
                    sendInfo(event.data.time);
                    break;
            }
        }

        function onWindowResize() {
            iframeRef.current?.contentWindow?.postMessage(
                { type: 'resize' },
                '*',
            );
        }

        window.addEventListener('message', onWindowMessage);
        window.addEventListener('resize', onWindowResize);

        return () => {
            window.removeEventListener('message', onWindowMessage);
            window.removeEventListener('resize', onWindowResize);
        };
    }, [resizeIframe, sendInfo]);

    return (
        <iframe
            className="w-full overflow-hidden"
            ref={iframeRef}
            src={embedUrl}
        />
    );
}

// src/lib/components/OveItEmbed.svelte
<script lang="ts">
    /* global HTMLIFrameElement, MessageEvent, window */
    import { onMount } from 'svelte';
    import { buildOveItIframeState } from '#lib/oveit.ts';

    interface Props {
        embedUrl: string;
    }

    let { embedUrl }: Props = $props();

    let iframe: HTMLIFrameElement | undefined = $state();
    let iframeSrc: string | undefined = $state();
    let embedId: string | undefined = $state();

    function sendInfo(time: number) {
        iframe?.contentWindow?.postMessage(
            {
                type: 'info',
                referrer: window.location.href,
                embedID: embedId,
                time,
            },
            '*',
        );
    }

    function resizeIframe(height: unknown) {
        if (!iframe) {
            return;
        }

        const parsedHeight = Number(height);
        iframe.style.height = `${Number.isNaN(parsedHeight) ? 800 : parsedHeight}px`;
    }

    onMount(() => {
        const iframeState = buildOveItIframeState(
            embedUrl,
            window.location.hash,
        );

        if (!iframeState) {
            return;
        }

        embedId = iframeState.embedId;
        iframeSrc = iframeState.iframeUrl.toString();

        function onWindowMessage(event: MessageEvent) {
            if (event.source !== iframe?.contentWindow) {
                return;
            }

            switch (event.data?.type) {
                case 'resize':
                    resizeIframe(event.data.height);
                    break;
                case 'info':
                    sendInfo(event.data.time);
                    break;
            }
        }

        function onWindowResize() {
            iframe?.contentWindow?.postMessage({ type: 'resize' }, '*');
        }

        window.addEventListener('message', onWindowMessage);
        window.addEventListener('resize', onWindowResize);

        return () => {
            window.removeEventListener('message', onWindowMessage);
            window.removeEventListener('resize', onWindowResize);
        };
    });
</script>

{#if iframeSrc}
    <iframe
        bind:this={iframe}
        title="Registration"
        class="w-full overflow-hidden"
        src={iframeSrc}
    ></iframe>
{:else}
    Loading...
{/if}
