// frontend/src/components/contentBlocks/TextWithButtonsBlock.tsx
import type { TextWithButtonsBlock } from '@/data/types';
import { RichText } from '@/components/RichText';
import { Button } from '@/components/Button';

export interface TextWithButtonsBlockProps {
    block: TextWithButtonsBlock;
}

export function TextWithButtonsBlock({ block }: TextWithButtonsBlockProps) {
    const text = block.properties?.text?.markup;
    const buttons = block.properties?.buttons ?? [];

    return (
        <section className="my-12 sm:my-20">
            <div className="small-content-container">
                {text ? <RichText className="mb-5" markup={text} /> : null}
                <div className="flex space-x-3">
                    {buttons.map((button, index) => (
                        <Button key={index} cmsLink={button}>
                            {button.title}
                        </Button>
                    ))}
                </div>
            </div>
        </section>
    );
}

// src/lib/components/TextWithButtonsBlock.svelte
<script lang="ts">
    import type { TextWithButtonsBlock } from '#lib/types.ts';
    import Button from './Button.svelte';
    import RichText from './RichText.svelte';

    interface Props {
        block: TextWithButtonsBlock;
    }

    let { block }: Props = $props();

    const text = $derived(block.properties?.text?.markup);
    const buttons = $derived(block.properties?.buttons ?? []);
</script>

<section class="my-12 sm:my-20">
    <div class="small-content-container">
        {#if text}
            <RichText class="mb-5" markup={text} />
        {/if}
        <div class="flex space-x-3">
            {#each buttons as button, index (button.destinationId ?? button.url ?? index)}
                <Button cmsLink={button}>{button.title}</Button>
            {/each}
        </div>
    </div>
</section>
